### ISSUE TITLE
public void delete(String docId) metodunda hata

### ISSUE THREAD

**Issue by BerdinEge** [umon/MongolabHelper#1]
Hocam altlarda yer alan bu metodun ;
public void delete(String docId) {
        this.oid = docId;
        this.requestMethod = "DELETE";
        this.url = toURL(getDocumentURL(docId));
        execute();
    }

this.oid kısmı hatalı sanırım. Orası ne olarak düzeltilmesi gerekiyor ?

**Comment by umon** [comment]
Fazladan kod parçası kalmış diyelim :)
Hazır elim değmişken; MongoLab api url'i de güncelledim.
